apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopdb-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopdb
  template:
    metadata:
      labels:
        app: shopdb
    spec:
      containers:
        - name: shopdb
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: shopdb-srv
spec:
  selector:
    app: shopdb
  ports:
    - name: shopdb
      protocol: TCP
      port: 27017
      targetPort: 27017
