apiVersion: apps/v1
kind: Deployment
metadata:
  name: transportationdb-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transportationdb
  template:
    metadata:
      labels:
        app: transportationdb
    spec:
      containers:
        - name: transportationdb
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: transportationdb-srv
spec:
  selector:
    app: transportationdb
  ports:
    - name: transportationdb
      protocol: TCP
      port: 27017
      targetPort: 27017
